---
core:
    num_workers: 10


inventory:
    plugin: nornir.plugins.inventory.simple.SimpleInventory
    options:
        host_file: "/home/ipvzero/Nornir2/hosts.yaml"
        group_file: "/home/ipvzero/Nornir2/groups.yaml"
        defaults_file: "/home/ipvzero/Nornir2/defaults.yaml"
